resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'vs2017-win2016'

stages:
- stage: Build
  displayName: Build Hugo Site
  jobs:
    - job: Build
      displayName: Build
      steps:
        - checkout: self
          displayName: 'Checkout repository including submodules'
          submodules: true
        - task: HugoTask@1
          displayName: 'Generate Hugo site'
          inputs:
            destination: '$(Build.ArtifactStagingDirectory)'
            baseURL: 'https://blog.iamdavidfrancis.com/'
        - task: PublishPipelineArtifact@0
          displayName: 'Publish Hugo site as an artifact'
          inputs:
            artifactName: 'hugo-site'
            targetPath: '$(Build.ArtifactStagingDirectory)'